config/routes.rb
Rails.application.routes.draw do



  resources :events do
      resources :comments
      get 'liked/', to: 'events#liked'
      get 'unliked/', to: 'events#unliked'
      member do
      get :attendees
    end
  end

  #Chat routes
  get 'chat/index'
  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
    
    member do
      post :close
    end
  end

  resources :attends, only: [:create, :destroy]

  
  #Follow and Unfollow routes
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations' }


  resources :users do
    member do
      get :attending
    end
  end


  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root 'events#index'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	 before_action :authenticate_user!
	 before_action :set_user
	 before_action :owned_profile, only: [:edit, :update]

  def show
  	@user = User.find_by(username: params[:username])
  	@events = User.find_by(username: params[:username]).events.order('created_at DESC')
  end

  def edit
	  @user = User.find_by(username: params[:username])
	end

	def update
		 @user = User.find_by(username: params[:username])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.username)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
	end

	private

		def profile_params
		  params.require(:user).permit(:avatar, :description)
		end

		def owned_profile
	    @user = User.find_by(username: params[:username])
	    unless current_user == @user
	      flash[:alert] = "That profile doesn't belong to you!"
	      redirect_to root_path
	    end
	  end

	  def set_user
	  	@user = User.find_by(username: params[:username])
	 end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
	 def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/profiles/edit.html.erb
<div class="events wrapper">
  <div class="event">
    <div class="event-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="small-12 medium-12 large-12">
              <div class="form-group text-center">
                <h4>Change your profile avatar</h4>
                  <div class="img-circle">
                    <%= profile_avatar_select(@user) %>
                  <%= f.file_field :avatar, onChange: 'loadFile(event' %>
                  </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="small-12 medium-12 large-12">
              <div class="form-group text-center">
                <h4>Update your description</h4>
                  <%= f.text_area :description, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'button button-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

         

app/views/profiles/show.html.erb
<div class="events-wrapper">
	<div class="row profile-header">
		<div class="small-12 medium-6 large-6">
			<div class="img-circle">
				<%= profile_avatar_select(@user) %>
			</div>
		</div>
		<div class="small-12 medium-6 large-6">
			<div class="user-name-and-follow">
				<h3 class="profile-user-name">
					<%= @user.username %>
				</h3>
				<span>
						<% if @user == current_user %>
						  <%= link_to 'Edit Profile', edit_profile_path(@user.username), class: 'button edit-button' %>
						<% else %>
						  <% if current_user_is_following(current_user.id, @user.id) %>
						    <%= link_to 'Following', unfollow_user_path, remote: true,
						      class: 'button unfollow-button', id: 'unfollow-button', method: :post %>
						  <% else %>
						    <%= link_to 'Follow', follow_user_path, remote: true, class: 'button follow-button', id: 'unfollow-button', method: :post %>
						  <% end %>
						<% end %>
				</span>
			</div>
			<p class="profile-description">
				<%= @user.description %>
			</p>
			<div class="user-statistics">
				<ul class="list-inline list-unstyled">
          <li>
            <strong><%= @user.events.count %></strong> 
            <%= "event".pluralize(@user.events.count)%>
          </li>
          <li>
            <strong><%= @user.followers.count %></strong> 
            <%= "follower".pluralize(@user.followers.count)%>
          </li>
          <li>
            <strong><%= @user.following.count %></strong> 
            <%= "following" %>
          </li>
        </ul>
			</div>
		</div>
	</div>
</div>

<% @events.each do |event| %>
  <%= render 'events/event', event: event %>
<% end %>