config/routes.rb
Rails.application.routes.draw do



  resources :events do
      resources :comments
      get 'liked/', to: 'events#liked'
      get 'unliked/', to: 'events#unliked'
      member do
      get :attendees
    end
  end

  #Chat routes
  get 'chat/index'
  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
    
    member do
      post :close
    end
  end

  resources :attends, only: [:create, :destroy]

  
  #Follow and Unfollow routes
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations' }


  resources :users do
    member do
      get :attending
    end
  end


  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root 'events#index'

end

app/models/notification.rb
class Notification < ApplicationRecord
	validates :user_id, :notified_by_id, :event_id, :identifier, :notice_type, presence: true
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :event
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
	  @notification = Notification.find(params[:id])
	  @notification.update read: true
	  redirect_to event_path @notification.event
	end

	def index
	  @notifications = current_user.notifications.order('created_at DESC')
	end
	
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
  <%= link_to "#{notification.notified_by.username} has #{notification.notice_type}ed on your event", link_through_path(notification) %>
</li>

app/views/notifications/_notification_dropdown.html.erb
<div class="has-dropdown notification-dropdown">
  <a class="has-dropdown no-click">
    <%= current_user.notifications.where(read:false).count %>
    <span class="fi fi-flag"></span>
  </a>
  <ul class="dropdown">
    <li class="dropdown-header text-center">Notifications</li>
      <%= render current_user.notifications.where(read: false).order('created_at DESC').last(5) %>
    </li>
    <li class="divider" role="separator">
      <li class="text-center">
        <%= link_to "View All", notifications_path %>
      </li>
    </li>
  </ul>
</div>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="small-12 medium-6 large-12">
      <ul class="notification-index-list"></ul>
      <% @notifications.each do |notification| %>
        <%= render 'notification', notification: notification %>
      <% end %>
    </div>
  </div>
</div>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>