config/routes.rb
Rails.application.routes.draw do



  resources :events do
      resources :comments
      get 'liked/', to: 'events#liked'
      get 'unliked/', to: 'events#unliked'
      member do
      get :attendees
    end
  end

  #Chat routes
  get 'chat/index'
  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
    
    member do
      post :close
    end
  end

  resources :attends, only: [:create, :destroy]

  
  #Follow and Unfollow routes
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations' }


  resources :users do
    member do
      get :attending
    end
  end


  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root 'events#index'

end

app/models/event.rb
class Event < ApplicationRecord

	belongs_to :user
	validates :user_id, presence: true

	validates :image, presence: true

  validates :address, presence: true

  has_attached_file :image, styles: { :medium => "450x300" }
  validates :image, length: { minimum: 3, maximum: 300 }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :comments, dependent: :destroy

  scope :of_followed_users, -> (following_users) { where user_id: following_users }
	#Likes
	acts_as_votable
	#Notifications
  has_many :notifications, dependent: :destroy

  has_many :passive_attends, class_name: "Attend", foreign_key: "attended_event_id", dependent: :destroy
  has_many :attendees, through: :passive_attends, source: :attendee

  #Maps
  after_validation :exclude_united_states_text_from_address
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  private

    def exclude_united_states_text_from_address
      self.address = address.gsub!(/(united states)/i, " ").strip!.chomp!(",") if address.downcase.include?("united states")
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :authenticate_user!
	before_action :set_event, only: [:show, :edit, :update, :destroy]
	before_action :set_event_for_nested_object, only: [:liked, :unliked]
	before_action :owned_event, only: [:edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update, :destroy]


	def index
		@events = Event.all.order('created_at DESC').page params[:page]
		# @events = Event.of_followed_users(current_user.following).order('created_at DESC').page params[:page]
	end

	def new
		@event = current_user.events.build
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
			current_user.attend(@event)
			flash[:success] = "Your event has been created!"
			redirect_to events_path
		else
			flash.now[:alert] = "Your new event couldn't be created!  Please check the form."
			render :new
		end
	end

	def show
		@event = Event.find(params[:id])
		@hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end
	end

	def edit
	end

	def update
		if @event.update(event_params)
			flash[:success] = "Event updated."
			redirect_to events_path
		else
			flash.now[:alert] = "Update failed.  Please check the form."
			render :edit
		end
	end

	def destroy
		@event.destroy
		flash[:success] = "Post deleted"
		redirect_to events_path
	end

	def liked
		@event.liked_by current_user
		create_notification @event
		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end
	end

	def unliked
		@event.unliked_by current_user

		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end
	end

	def attendees
    @event  = Event.find(params[:id])
    @users = @event.attendees.paginate(page: params[:page])
  end


	private

	def event_params
		params.require(:event).permit(:image, :title, :description, :date, :price, :place, :address, :latitude, :longitude)
	end

	def set_event
    @event = Event.find(params[:id])
  end

	def set_event_for_nested_object
		@event = Event.find(params[:event_id])
	end


  def owned_event
	  unless current_user == @event.user
	    flash[:alert] = "That event doesn't belong to you!"
	    redirect_to root_path
	  end
	end

	def correct_user
    unless @event.user.id == current_user.id
      flash[:alert] = "That event doesn't belong to you!"
      redirect_to root_path
    end
  end
  
  def create_notification(event)
    return if event.user == current_user
    Notification.create(user_id: event.user.id,
                        notified_by_id: current_user.id,
                        event_id: event.id,
                        identifier: event.id,
                        notice_type: 'liked')
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def likes_helper(event, user)
    if user.voted_for?(event)
      event_unliked_url(event)
    else
      event_liked_url(event)
    end
  end

  def likes_icon(event, user)
    if user.voted_for?(event)
      "fi fi-heart full_heart"
    else
      "fi fi-heart empty_heart"
    end
  end
end

app/views/events/_attend.html.erb
<%= form_for(current_user.active_attends.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :attended_event_id, @event.id %></div>
  <p class="lead center"><%= f.submit "Attend Event", class: "button button-primary" %></p>
<% end %>

app/views/events/_event.html.erb
<div class="events-wrapper">
  <div class="event">
    <div class="event-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to event.user.username, profile_path(event.user.username) %>
      </div>
      <%= event.title %>
      <div class="time-ago">
        <%= time_ago_in_words event.created_at %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag event.image.url(:medium), class:'img-responsive'), event_path(event) %>
    </div>
    <div class="event-bottom">
      <div class="caption">
        <div class="event_edit">
          <%= link_to likes_helper(event, current_user) ,id: "likes_#{event.id}", remote: true do%>
            <i class="<%= likes_icon(event, current_user)%>"></i>
          <% end %>
          <span><%= event.get_likes.size%></span>
        </div>
        <div class="share">
          <%= social_share_button_tag(image_tag event.image.url) %>
        </div>
      </div>
      <div class="comments" id="comments_<%= event.id %>">
        <% if event.comments.any? %>
          <div class="paginator" id="#comments-paginator-<%= event.id %>">
            <% unless event.comments.count <= 4 %>
              <%= link_to "view all #{event.comments.count} comments", event_comments_path(event), remote: true, class: 'more-comments', data: {event_id: "#{event.id}", type: "html"} %>
            <% end %>
          </div>
          <%= render event.comments.last(4), event: event %>
        <% end %>
      </div>

    </div>
    </div>
    <div class="comment-like-form">
      <div class="comment-form col-sm-11">
        <%= form_for [event, event.comments.build] , remote: true do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{event.id}"%>
        <% end %>
      </div>
    </div>

    <div class="attendees">
      <% if event.date > Time.now %>
        <p><%= pluralize(event.attendees.count, 'person') %> attending</p>
      <% else %>
          <p><%= pluralize(event.attendees.count, 'person') %> attended</p>
      <% end %>
    </div>
</div>

app/views/events/_form.html.erb
<% content_for :head do %>
	<%= javascript_include_tag 'google-places.js' %>
<% end %>

<%= image_tag @event.image.url(:medium) %>
<%= simple_form_for @event do |f| %>
	<%= f.input :image %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.datetime_select :date %>
	<%= f.input :price %>
	<%= f.input :place, collection: 1..10 %>
	<div class="address">
		<%= f.label :address, "Address / Location" %><span id="required">*</span>
    <%= f.text_field :address, class: "form-control", id: "txtautocomplete" %>
	</div>
	<%= f.button :submit %>
<% end %>

app/views/events/_unattend.html.erb
<%= form_for(current_user.active_attends.find_by(attended_event_id: @event.id), html: { method: :delete }, remote: true) do |f| %>
  <p class="lead" style="text-align:center;"><%= f.submit "Unattend Event", class: "button button-primary" %></p>
<% end %>

app/views/events/edit.html.erb
<%= render 'form' %>

<%= link_to "Delete", event_path(@event), method: :delete, date: { confirm: "Are you sure you want to delete this post?" } %>
<%= link_to "Cancel", events_path %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <%= render 'event', event: event %>
<% end %>
	<%= link_to_next_page @events, 'LOAD MORE', remote: true, id: 'load_more' %>

app/views/events/index.js.erb
$('#events').append("<%= escape_javascript(render 'events')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@events, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/events/liked.js.erb
$('#likes_<%= @event.id %> > i').toggleClass('empty_heart full_heart')
$('#likes_<%= @event.id %> + spann').val('<%= @event.get_likes.size %>')

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<%= render 'event', event: @event %>
  <div class="small-12 medium-6 large-4">
    <div class="well" id="event-sidebar">
      <p class="lead"><b>Location:</b> <%= @event.address %></p>
      <div id="map"></div>
    </div>
  </div>
	<!-- Attendees -->
  <% if @event.date > Time.now %> 
    <p class="lead center">People attending this event (<span id="attendees"><%= @event.attendees.count %></span>)</p>
  <% else %>
    <p class="lead center" >People that attended this event (<span id="attendees"><%= @event.attendees.count %></span>)</p> 
  <% end %>
  <hr>
  <div id="users_attending" >
    <% @event.attendees.each do |user| %>
      <li style="text-align:center; list-style: none; font-size: 16px;">Name: <%= link_to user.username, user %></li>
    <% end %>
  </div>
	<% if @event.user.id == current_user.id %>
			<%= link_to "Cancel", events_path %>
			<%= link_to "Edit", edit_event_path(@event) %>
	<% else %>
			<div id="attend_form" >
        <% if current_user.attending?(@event) %>
          <%= render "unattend" %>
        <% else %>
          <%= render "attend" %>
        <% end %>
      </div>
			<%= link_to "Cancel", events_path %>
	<% end %>
  
<% content_for :javascript do %>
<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(15);
    });
  </script>
<% end %>

app/views/events/unliked.js.erb
$('#likes_<%= @event.id %> > i').toggleClass('empty_heart full_heart')
$('#likes_<%= @event.id %> + spann').val('<%= @event.get_likes.size %>')