config/routes.rb
Rails.application.routes.draw do



  resources :events do
      resources :comments
      get 'liked/', to: 'events#liked'
      get 'unliked/', to: 'events#unliked'
      member do
      get :attendees
    end
  end

  #Chat routes
  get 'chat/index'
  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
    
    member do
      post :close
    end
  end

  resources :attends, only: [:create, :destroy]

  
  #Follow and Unfollow routes
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations' }


  resources :users do
    member do
      get :attending
    end
  end


  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root 'events#index'

end

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
				<%= link_to "Unajua", root_path %>
		</li>

		<li class="toggle-topbar">
      <a href="#"><span>Menu</span></a>
    </li>
	</ul>
	
	<section class="top-bar-section">
    <ul class="right">
          <% if user_signed_in? %>
						 <li>
	            <%= render 'notifications/notification_dropdown' %>
	          </li>
	          <li>
	            <%= link_to "Messages", chat_index_path %>
	          </li>
	          <li>
	            <%= link_to "Profile", profile_path(current_user.username) %>
	          </li>
				    <li>
				      <%= link_to "New event", new_event_path %>
				    </li>
				    <li>
				      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
				    </li>
				    <% else %>
				    <li>
				      <%= link_to "Login", new_user_session_path %>
				    </li>
				    <li>
				      <%= link_to "Register", new_user_registration_path %>
				    </li>
		  <% end %>
    </ul>
  </section>

</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "unajua" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <!-- Google Maps API -->
  <script src="//maps.google.com/maps/api/js?key=AIzaSyBZ7ZhwVIUYWElrUzcGPx9bPUe3-2RhKXU&libraries=places"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="row">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
    </div>
    <div class="row">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>